version: "3"

services:
  front-end:
    build: ./CP_Discussion_Front-End
    ports:
      - 3000:3000
    depends_on:
      - back-end
    command: pnpm run dev

  back-end:
    build: ./CP_Discussion_Back-End
    ports:
      - 8080:8080
    volumes:
      - ~/apps/data:/app/data
    depends_on:
      - mongo-db

  mongo-db:
    image: mongo:latest
    restart: always
    ports:
      - ${DBPort}:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      TZ: ${DBTZ}
      MONGO_INITDB_ROOT_USERNAME: ${DBUsername}
      MONGO_INITDB_ROOT_PASSWORD: ${DBPassword}

  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo-db
    ports:
      - ${DBExpressPort}:8081
    environment:
      ME_CONFIG_OPTIONS_EDITORTHEME: 3024-night
      ME_CONFIG_MONGODB_SERVER: mongo-db
      ME_CONFIG_MONGODB_PORT: ${DBPort}
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DBUsername}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DBPassword}
